SELECT o.ID, o.QUEUE, o.STATUS, o.ORDER_CREATED, o.VERSION_ID 
FROM "PUBLIC".RECOVERY_ORDER o
WHERE o.ID IN (
 SELECT MIN(q.ID) FROM "PUBLIC".RECOVERY_ORDER q
 WHERE STATUS = 'SUCCESS' 
 GROUP BY q.QUEUE)
AND o.VERSION_ID IS NULL
ORDER BY o.ORDER_CREATED
